const CHANNEL_TYPES = Object.freeze({
    COMMAND: 'command',
    QUERY: 'query',
    STREAM: 'stream',
    LIFECYCLE: 'lifecycle',
});

const CHANNELS = Object.freeze({
    WINDOW_READY: 'window-lifecycle:ready',
    DESKTOP_REMOTE_REQUEST: 'desktop-remote:request',
    DESKTOP_REMOTE_RESPONSE: 'desktop-remote:response',
    FLOWLOCK_REQUEST: 'flowlock:request',
    FLOWLOCK_RESPONSE: 'flowlock:response',
    DESKTOP_LAUNCH: 'desktop-launch-vchat-app',
    AGENT_RUNTIME_GET_STATUS: 'agent-runtime:get-status',
    AGENT_RUNTIME_GET_PRESENTATION_MODE: 'agent-runtime:get-presentation-mode',
    AGENT_RUNTIME_START: 'agent-runtime:start',
    AGENT_RUNTIME_STOP: 'agent-runtime:stop',
    AGENT_RUNTIME_CREATE_TOPIC: 'agent-runtime:create-topic',
    AGENT_RUNTIME_CREATE_SESSION: 'agent-runtime:create-session',
    AGENT_RUNTIME_ENSURE_SESSION_RUNTIME: 'agent-runtime:ensure-session-runtime',
    AGENT_RUNTIME_FORK_SESSION: 'agent-runtime:fork-session',
    AGENT_RUNTIME_CLOSE_SESSION: 'agent-runtime:close-session',
    AGENT_RUNTIME_RESTORE_SESSION: 'agent-runtime:restore-session',
    AGENT_RUNTIME_SET_SESSION_PINNED: 'agent-runtime:set-session-pinned',
    AGENT_RUNTIME_COMPACT_SESSION: 'agent-runtime:compact-session',
    AGENT_RUNTIME_LIST_TOPICS: 'agent-runtime:list-topics',
    AGENT_RUNTIME_SEARCH_TOPICS: 'agent-runtime:search-topics',
    AGENT_RUNTIME_SEARCH_TOPIC_MESSAGES: 'agent-runtime:search-topic-messages',
    AGENT_RUNTIME_GET_TOPIC_INDEX_STATUS: 'agent-runtime:get-topic-index-status',
    AGENT_RUNTIME_REBUILD_TOPIC_INDEX: 'agent-runtime:rebuild-topic-index',
    AGENT_RUNTIME_READ_TOPIC: 'agent-runtime:read-topic',
    AGENT_RUNTIME_READ_PROJECTION: 'agent-runtime:read-projection',
    AGENT_RUNTIME_TAKEOVER_TOPIC: 'agent-runtime:takeover-topic',
    AGENT_RUNTIME_RENAME_TOPIC: 'agent-runtime:rename-topic',
    AGENT_RUNTIME_DELETE_TOPIC: 'agent-runtime:delete-topic',
    AGENT_RUNTIME_LIST_INTERACTION_QUEUE: 'agent-runtime:list-interaction-queue',
    AGENT_RUNTIME_REPLACE_INTERACTION_QUEUE: 'agent-runtime:replace-interaction-queue',
    AGENT_RUNTIME_CLEAR_INTERACTION_QUEUE: 'agent-runtime:clear-interaction-queue',
    AGENT_RUNTIME_GET_WORKBENCH_SETTINGS: 'agent-runtime:get-workbench-settings',
    AGENT_RUNTIME_UPDATE_WORKBENCH_SETTINGS: 'agent-runtime:update-workbench-settings',
    AGENT_RUNTIME_SELECT_ATTACHMENTS: 'agent-runtime:select-attachments',
    AGENT_RUNTIME_START_TURN: 'agent-runtime:start-turn',
    AGENT_RUNTIME_STEER_TURN: 'agent-runtime:steer-turn',
    AGENT_RUNTIME_FOLLOW_UP_TURN: 'agent-runtime:follow-up-turn',
    AGENT_RUNTIME_CANCEL_TURN: 'agent-runtime:cancel-turn',
    AGENT_RUNTIME_RESPOND_APPROVAL: 'agent-runtime:respond-approval',
    AGENT_RUNTIME_RESPOND_INTERACTION: 'agent-runtime:respond-interaction',
    AGENT_RUNTIME_SET_WORKBENCH_PRESENCE: 'agent-runtime:set-workbench-presence',
    AGENT_RUNTIME_EVENT: 'agent-runtime:event',
});

const channelRegistry = new Map([
    [CHANNELS.WINDOW_READY, {
        channelName: CHANNELS.WINDOW_READY,
        channelType: CHANNEL_TYPES.LIFECYCLE,
        owner: 'VChat Shell',
        requestSchema: { appId: 'string', payload: 'object?' },
        responseSchema: null,
        supportsConcurrent: true,
    }],
    [CHANNELS.DESKTOP_REMOTE_REQUEST, {
        channelName: CHANNELS.DESKTOP_REMOTE_REQUEST,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'VDesktop Platform',
        requestSchema: { requestId: 'string', command: 'string', payload: 'object?' },
        responseSchema: { requestId: 'string', ok: 'boolean', data: 'object?', error: 'string?' },
        supportsConcurrent: true,
    }],
    [CHANNELS.DESKTOP_REMOTE_RESPONSE, {
        channelName: CHANNELS.DESKTOP_REMOTE_RESPONSE,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'VDesktop Platform',
        requestSchema: { requestId: 'string', ok: 'boolean', data: 'object?', error: 'string?' },
        responseSchema: null,
        supportsConcurrent: true,
    }],
    [CHANNELS.FLOWLOCK_REQUEST, {
        channelName: CHANNELS.FLOWLOCK_REQUEST,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'VChat Shell',
        requestSchema: { requestId: 'string', command: 'string', payload: 'object?' },
        responseSchema: { requestId: 'string', ok: 'boolean', data: 'object?', error: 'string?' },
        supportsConcurrent: true,
    }],
    [CHANNELS.FLOWLOCK_RESPONSE, {
        channelName: CHANNELS.FLOWLOCK_RESPONSE,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'VChat Shell',
        requestSchema: { requestId: 'string', ok: 'boolean', data: 'object?', error: 'string?' },
        responseSchema: null,
        supportsConcurrent: true,
    }],
    [CHANNELS.DESKTOP_LAUNCH, {
        channelName: CHANNELS.DESKTOP_LAUNCH,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'VChat Shell',
        requestSchema: { appAction: 'string' },
        responseSchema: { success: 'boolean', appId: 'string?' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_GET_STATUS, {
        channelName: CHANNELS.AGENT_RUNTIME_GET_STATUS,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: null,
        responseSchema: { state: 'string', protocolVersion: 'number', worker: 'object?', attachment: 'object?' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_GET_PRESENTATION_MODE, {
        channelName: CHANNELS.AGENT_RUNTIME_GET_PRESENTATION_MODE,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: null,
        responseSchema: { mode: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_START, {
        channelName: CHANNELS.AGENT_RUNTIME_START,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: null,
        responseSchema: { state: 'string', protocolVersion: 'number', worker: 'object?' },
        supportsConcurrent: false,
    }],
    [CHANNELS.AGENT_RUNTIME_STOP, {
        channelName: CHANNELS.AGENT_RUNTIME_STOP,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: null,
        responseSchema: { state: 'string' },
        supportsConcurrent: false,
    }],
    [CHANNELS.AGENT_RUNTIME_CREATE_TOPIC, {
        channelName: CHANNELS.AGENT_RUNTIME_CREATE_TOPIC,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { agent: 'string', title: 'string?', model: 'string?', workspaceRoot: 'string?' },
        responseSchema: { topicId: 'string', agentId: 'string', title: 'string', model: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_CREATE_SESSION, {
        channelName: CHANNELS.AGENT_RUNTIME_CREATE_SESSION,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { workspaceRoot: 'string?', model: 'string?', metadata: 'object?' },
        responseSchema: { sessionId: 'string', state: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_ENSURE_SESSION_RUNTIME, {
        channelName: CHANNELS.AGENT_RUNTIME_ENSURE_SESSION_RUNTIME,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { sessionId: 'string', reason: 'string?' },
        responseSchema: { sessionId: 'string', threadId: 'string', state: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_START_TURN, {
        channelName: CHANNELS.AGENT_RUNTIME_START_TURN,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        // At least one of prompt or attachments is required; that cross-field
        // invariant is enforced by RustDaemonTransport and the daemon schema.
        requestSchema: { sessionId: 'string', prompt: 'string?', attachments: 'array?' },
        responseSchema: { turnId: 'string', state: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_SELECT_ATTACHMENTS, {
        channelName: CHANNELS.AGENT_RUNTIME_SELECT_ATTACHMENTS,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { sessionId: 'string' },
        responseSchema: { attachments: 'array' },
        supportsConcurrent: false,
    }],
    [CHANNELS.AGENT_RUNTIME_CANCEL_TURN, {
        channelName: CHANNELS.AGENT_RUNTIME_CANCEL_TURN,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { sessionId: 'string', turnId: 'string?' },
        responseSchema: { ok: 'boolean' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_RESPOND_APPROVAL, {
        channelName: CHANNELS.AGENT_RUNTIME_RESPOND_APPROVAL,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { approvalId: 'string', decision: 'string', scope: 'string?', reason: 'string?', sessionId: 'string?', turnId: 'string?', toolCallId: 'string?', argumentsHash: 'string?' },
        responseSchema: { approvalId: 'string', decision: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_RESPOND_INTERACTION, {
        channelName: CHANNELS.AGENT_RUNTIME_RESPOND_INTERACTION,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: { source: 'string', requestId: 'string', kind: 'string', response: 'object' },
        responseSchema: { requestId: 'string', resolved: 'boolean', kind: 'string' },
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_SET_WORKBENCH_PRESENCE, {
        channelName: CHANNELS.AGENT_RUNTIME_SET_WORKBENCH_PRESENCE,
        channelType: CHANNEL_TYPES.COMMAND,
        owner: 'Agent Runtime',
        requestSchema: { mounted: 'boolean' },
        responseSchema: null,
        supportsConcurrent: true,
    }],
    [CHANNELS.AGENT_RUNTIME_EVENT, {
        channelName: CHANNELS.AGENT_RUNTIME_EVENT,
        channelType: CHANNEL_TYPES.STREAM,
        owner: 'Agent Runtime',
        requestSchema: null,
        responseSchema: null,
        supportsConcurrent: true,
    }],
]);

// Agent runtime control-plane queries. Electron validates IPC origin and
// forwards the runtime-owned response without creating a second transcript.
for (const channel of [
    CHANNELS.AGENT_RUNTIME_FORK_SESSION,
    CHANNELS.AGENT_RUNTIME_CLOSE_SESSION,
    CHANNELS.AGENT_RUNTIME_RESTORE_SESSION,
    CHANNELS.AGENT_RUNTIME_SET_SESSION_PINNED,
    CHANNELS.AGENT_RUNTIME_COMPACT_SESSION,
    CHANNELS.AGENT_RUNTIME_LIST_TOPICS,
    CHANNELS.AGENT_RUNTIME_SEARCH_TOPICS,
    CHANNELS.AGENT_RUNTIME_SEARCH_TOPIC_MESSAGES,
    CHANNELS.AGENT_RUNTIME_GET_TOPIC_INDEX_STATUS,
    CHANNELS.AGENT_RUNTIME_REBUILD_TOPIC_INDEX,
    CHANNELS.AGENT_RUNTIME_READ_TOPIC,
    CHANNELS.AGENT_RUNTIME_READ_PROJECTION,
    CHANNELS.AGENT_RUNTIME_TAKEOVER_TOPIC,
    CHANNELS.AGENT_RUNTIME_RENAME_TOPIC,
    CHANNELS.AGENT_RUNTIME_DELETE_TOPIC,
    CHANNELS.AGENT_RUNTIME_LIST_INTERACTION_QUEUE,
    CHANNELS.AGENT_RUNTIME_REPLACE_INTERACTION_QUEUE,
    CHANNELS.AGENT_RUNTIME_CLEAR_INTERACTION_QUEUE,
    CHANNELS.AGENT_RUNTIME_GET_WORKBENCH_SETTINGS,
    CHANNELS.AGENT_RUNTIME_UPDATE_WORKBENCH_SETTINGS,
    CHANNELS.AGENT_RUNTIME_STEER_TURN,
    CHANNELS.AGENT_RUNTIME_FOLLOW_UP_TURN,
]) {
    channelRegistry.set(channel, {
        channelName: channel,
        channelType: CHANNEL_TYPES.QUERY,
        owner: 'Agent Runtime',
        requestSchema: 'runtime-command-payload?',
        responseSchema: 'runtime-control-result',
        supportsConcurrent: true,
    });
}

function getChannelMeta(channelName) {
    return channelRegistry.get(channelName) || null;
}

function listChannels() {
    return Array.from(channelRegistry.values());
}

module.exports = {
    CHANNELS,
    CHANNEL_TYPES,
    getChannelMeta,
    listChannels,
};
