'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const parser=require('@babel/parser');
function functionSource(file,name){const source=fs.readFileSync(path.join(__dirname,'..',file),'utf8');const ast=parser.parse(source,{sourceType:'unambiguous'});let found;function walk(n){if(!n||typeof n!=='object')return;if(n.type==='FunctionDeclaration'&&n.id.name===name)found=source.slice(n.start,n.end);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v?.type)walk(v);}walk(ast);if(!found)throw Error(name);return found;}
function backend(){let history=[],writes=0,release;let configGate=Promise.resolve();const events=[];const context={console:{log(){},error(){}},queuedUserAdmissions:new Map(),createGroupQueueContext:()=>({}),mainAppPaths:{AGENT_GROUPS_DIR:'groups',AGENT_DIR:'agents',USER_DATA_DIR:'user'},getAgentGroupConfig:async()=>{await configGate;return{members:[]};},path,fs:{ensureDir:async()=>{},pathExists:async()=>true,readJson:async()=>history},getVcpGlobalSettings:async()=>({}),tavernHandlers:{},appendGroupHistoryMessage:async(g,t,m)=>{writes++;history=[...history,m];return history;},setGroupStreamCallback(){},Date};
const code=functionSource('Groupmodules/groupchat.js','handleGroupChatMessage')+'\n'+functionSource('Groupmodules/groupchat.js','performGroupChatMessage')+'\nthis.send=handleGroupChatMessage';vm.runInNewContext(code,context);
return{context,send:id=>context.send('g','t',{id,name:'U',content:{text:'queue body'}},event=>events.push(event),async()=>null),get writes(){return writes;},hold(){configGate=new Promise(r=>{release=r;});},release(){release();},history:()=>history};}
test('group stable admission ID shares concurrent work and skips durable replay',async()=>{const b=backend();b.hold();const first=b.send('queue-1'),second=b.send('queue-1');b.release();await Promise.all([first,second]);assert.equal(b.writes,1);await b.send('queue-1');assert.equal(b.writes,1);assert.equal(b.history()[0].content,'queue body');});
test('group validation and failed persistence reject admission',async()=>{const b=backend();b.context.getAgentGroupConfig=async()=>null;await assert.rejects(b.send('bad'),/未找到群组配置/);assert.equal(b.writes,0);const c=backend();c.context.appendGroupHistoryMessage=async()=>{throw Error('disk-full');};await assert.rejects(c.send('disk'),/disk-full/);assert.equal(c.history().length,0);});
